### ISSUE TITLE
笔记

### ISSUE THREAD

**Issue by bddjr** [bddjr/hlfhr#2]
昨天我甚至想看看go的http标准库还能不能改的更规范点，通过正确的途径解析发送到HTTPS端口的HTTP请求，然而看了几遍后放弃了。

这东西写的时候根本没考虑从TLS握手回退到HTTP1.1，标准库就只是简单写入400然后关闭连接，这东西真正改起来很费精力，所以这问题从2021年到现在，标准库还是没解决，我只能在这基础上写个第三方库继续堆屎

**Comment by dbkuaizi** [comment]
有个小问题啊哥们 go.mod 里面的依赖版本可以调低点吗，这个功能应该用不到这么新的版本（当然我明白这个 go.mod 是 init 的时候自动生成的）。
大部分开发可能是 1.20 或者 1.21 的版本 go get 之后还得改一下 go.mod。

**Comment by bddjr** [comment]
你用1.20测试没有问题对吗

**Comment by bddjr** [comment]
如果您用go1.20能过编译，我可以改

**Comment by dbkuaizi** [comment]
我的开发环境是 go version go1.21.12 windows/amd64，没有任何问题。

1.20 大概率也没有问题，这两个版本在 net 库方面没有修改太多东西。

因为 我 go get  的时候老提示我升级 1.22，所以我是 直接下载的项目文件 然后引入的，没有走 mod 包管理

**Comment by bddjr** [comment]
改成go1.21了，你现在再试试
```
go get github.com/bddjr/hlfhr@v0.2.3
```

**Comment by dbkuaizi** [comment]
试过了 可以正常编译 没有问题

**Comment by bddjr** [comment]
好
